version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GYWBE8A7S9RMVPHATGD5JSN8 --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYWBE8A7S9RMVPHATGD5JSN8/input_ethnicity.csv.gz

  generate_study_population_weekly_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="weekly"
      --param time_value="10"
      --param time_ever="False"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="all"
      --param breakdowns=""
      --index-date_range="2023-04-10 to 2023-04-10 by week"
      --output-dir=output/01GYWBE8A7S9RMVPHATGD5JSN8
      --output-format=csv.gz
      --output-file=output/01GYWBE8A7S9RMVPHATGD5JSN8/input_weekly_2023-04-10.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYWBE8A7S9RMVPHATGD5JSN8/input_weekly_2023-04-10.csv.gz

  generate_study_population_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="10"
      --param time_ever="False"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="all"
      --param breakdowns="sex,age,ethnicity,imd,region"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GYWBE8A7S9RMVPHATGD5JSN8
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYWBE8A7S9RMVPHATGD5JSN8/input_*.csv.gz

  join_cohorts_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GYWBE8A7S9RMVPHATGD5JSN8/input_20*.csv.gz
        --rhs output/01GYWBE8A7S9RMVPHATGD5JSN8/input_ethnicity.csv.gz
        --output-dir output/01GYWBE8A7S9RMVPHATGD5JSN8/joined
    needs: [generate_study_population_01GYWBE8A7S9RMVPHATGD5JSN8, generate_study_population_ethnicity_01GYWBE8A7S9RMVPHATGD5JSN8]
    outputs:
      highly_sensitive:
        cohort: output/01GYWBE8A7S9RMVPHATGD5JSN8/joined/input_20*.csv.gz

  generate_measures_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01GYWBE8A7S9RMVPHATGD5JSN8/joined"

    needs: [join_cohorts_01GYWBE8A7S9RMVPHATGD5JSN8]
    outputs:
      moderately_sensitive:
        measure: output/01GYWBE8A7S9RMVPHATGD5JSN8/joined/measure_all.csv
        decile_measure: output/01GYWBE8A7S9RMVPHATGD5JSN8/joined/measure_practice_rate_deciles.csv

  top_5_table_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GYWBE8A7S9RMVPHATGD5JSN8"
    needs: [generate_measures_01GYWBE8A7S9RMVPHATGD5JSN8]
    outputs:
      moderately_sensitive:
        tables: output/01GYWBE8A7S9RMVPHATGD5JSN8/joined/top_5*.csv

  plot_measure_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --output-dir output/01GYWBE8A7S9RMVPHATGD5JSN8
    needs: [generate_measures_01GYWBE8A7S9RMVPHATGD5JSN8]
    outputs:
      moderately_sensitive:
        measure: output/01GYWBE8A7S9RMVPHATGD5JSN8/plot_measure*.png
        deciles: output/01GYWBE8A7S9RMVPHATGD5JSN8/deciles_chart.png

  event_counts_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: >
      python:latest python analysis/event_counts.py --input-dir="output/01GYWBE8A7S9RMVPHATGD5JSN8" --output-dir="output/01GYWBE8A7S9RMVPHATGD5JSN8"
    needs: [join_cohorts_01GYWBE8A7S9RMVPHATGD5JSN8, generate_study_population_weekly_01GYWBE8A7S9RMVPHATGD5JSN8]
    outputs:
      moderately_sensitive:
        measure: output/01GYWBE8A7S9RMVPHATGD5JSN8/event_counts.json

  generate_report_01GYWBE8A7S9RMVPHATGD5JSN8:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GYWBE8A7S9RMVPHATGD5JSN8"
      --population="all"
      --breakdowns=sex
      --breakdowns=age
      --breakdowns=ethnicity
      --breakdowns=imd
      --breakdowns=region
      --codelist-1-name="Non-high dose long acting opioids (OpenPrescribing) -  dm+d"
      --codelist-2-name="Sickle (SPL-AtRiskv4) (SNOMED CT)"
      --codelist-1-link="opensafely/non-high-dose-long-acting-opioids-openprescribing-dmd/39e300ce"
      --codelist-2-link="nhsd/sickle-spl-atriskv4-snomed-ct/7083ed37"
      --time-value="10"
      --time-scale="years"
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
    needs: [event_counts_01GYWBE8A7S9RMVPHATGD5JSN8, top_5_table_01GYWBE8A7S9RMVPHATGD5JSN8, plot_measure_01GYWBE8A7S9RMVPHATGD5JSN8]
    outputs:
      moderately_sensitive:
        notebook: output/01GYWBE8A7S9RMVPHATGD5JSN8/report.html