version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GZ0RDNT16YZ3MJQSJF8FHSYH --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/input_ethnicity.feather

  generate_study_population_weekly_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="weekly"
      --param time_value="None"
      --param time_ever="True"
      --param time_scale=""
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="all"
      --param breakdowns=""
      --index-date_range="2023-04-10 to 2023-04-10 by week"
      --output-dir=output/01GZ0RDNT16YZ3MJQSJF8FHSYH
      --output-format=feather
      --output-file=output/01GZ0RDNT16YZ3MJQSJF8FHSYH/input_weekly_2023-04-10.feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/input_weekly_2023-04-10.feather

  generate_study_population_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="None"
      --param time_ever="True"
      --param time_scale=""
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="all"
      --param breakdowns="sex,age,ethnicity,imd,region"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GZ0RDNT16YZ3MJQSJF8FHSYH
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/input_*.feather

  join_cohorts_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GZ0RDNT16YZ3MJQSJF8FHSYH/input_20*.feather
        --rhs output/01GZ0RDNT16YZ3MJQSJF8FHSYH/input_ethnicity.feather
        --output-dir output/01GZ0RDNT16YZ3MJQSJF8FHSYH/joined
    needs: [generate_study_population_01GZ0RDNT16YZ3MJQSJF8FHSYH, generate_study_population_ethnicity_01GZ0RDNT16YZ3MJQSJF8FHSYH]
    outputs:
      highly_sensitive:
        cohort: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/joined/input_20*.feather

  generate_measures_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01GZ0RDNT16YZ3MJQSJF8FHSYH/joined"

    needs: [join_cohorts_01GZ0RDNT16YZ3MJQSJF8FHSYH]
    outputs:
      moderately_sensitive:
        measure: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/joined/measure_all.csv
        decile_measure: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/joined/measure_practice_rate_deciles.csv

  top_5_table_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GZ0RDNT16YZ3MJQSJF8FHSYH"
    needs: [generate_measures_01GZ0RDNT16YZ3MJQSJF8FHSYH]
    outputs:
      moderately_sensitive:
        tables: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/joined/top_5*.csv

  plot_measure_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --output-dir output/01GZ0RDNT16YZ3MJQSJF8FHSYH
    needs: [generate_measures_01GZ0RDNT16YZ3MJQSJF8FHSYH]
    outputs:
      moderately_sensitive:
        measure: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/plot_measure*.png
        deciles: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/deciles_chart.png

  event_counts_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01GZ0RDNT16YZ3MJQSJF8FHSYH" --output-dir="output/01GZ0RDNT16YZ3MJQSJF8FHSYH"
    needs: [join_cohorts_01GZ0RDNT16YZ3MJQSJF8FHSYH, generate_study_population_weekly_01GZ0RDNT16YZ3MJQSJF8FHSYH]
    outputs:
      moderately_sensitive:
        measure: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/event_counts.json

  generate_report_01GZ0RDNT16YZ3MJQSJF8FHSYH:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GZ0RDNT16YZ3MJQSJF8FHSYH"
      --population="all"
      --breakdowns=sex
      --breakdowns=age
      --breakdowns=ethnicity
      --breakdowns=imd
      --breakdowns=region
      --codelist-1-name="Phenoxymethylpenicillin (oral preparations only)"
      --codelist-2-name="Sickle (SPL-AtRiskv4) (SNOMED CT)"
      --codelist-1-link="opensafely/phenoxymethylpenicillin-oral-preparations-only/14b427f8"
      --codelist-2-link="nhsd/sickle-spl-atriskv4-snomed-ct/7083ed37"
      --time-value="None"
      --time-scale=""
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
      
      --time-ever
      
    needs: [event_counts_01GZ0RDNT16YZ3MJQSJF8FHSYH, top_5_table_01GZ0RDNT16YZ3MJQSJF8FHSYH, plot_measure_01GZ0RDNT16YZ3MJQSJF8FHSYH]
    outputs:
      moderately_sensitive:
        notebook: output/01GZ0RDNT16YZ3MJQSJF8FHSYH/report.html